TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'TYPO3.Neos.Seo': TRUE

    userInterface:
      translation:
        autoInclude:
          'TYPO3.Neos.Seo': ['NodeTypes/*']

    Seo:
      # Twitter Card settings
      twitterCard:
        # the Twitter handle for the twitter:site attribution
        siteHandle: ~
